debug: true

pumpk1n:
  data-folder: "./plugins/NostalgiaManager/data/"

modules:
  enhanced-chat:
    enabled: true
    ping-sound: CHICKEN_EGG_POP
  world-border:
    enabled: false
    distances:
      overworld: 10_000
      nether: 1250
      end: 10_000
    ignore-creative: true
    ignore-ops: true
  mob-limiter:
    enabled: true
    entity-limit: 50
    check-every-ticks: 600
    ignored-worlds:
      - the_end
