name: NostalgiaManager
version: 1.0.0
main: dev.mayuna.nostalgiamanager.Main
authors: [ Mayuna ]

commands:
  nostalgia-reload:
    description: Reloads plugin's config
    usage: /nostalgia-reload
    permission: nostalgiamanager.admin
  chat-pings:
    description: Allows you to configure chat pings for yourself
    usage: /chat-pings <on|off>